### ISSUE TITLE
Schema dati - campo "quarantena"

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#10]
Buongiorno a tutti/e, nel form per il data entry avevo predisposto un campo per inserire le persone **attualmente in quarantena*** ma nello schema dati concordato con @gabacode non se ne fa riferimento. Procedo all'eliminazione del campo "quarantena" dal form oppure pensate possa essere un'informazione importante che potremmo implementare nello schema dati? 

***attualmente in quarantena** = attualmente positivi in isolamento domiciliare + contatti stretti non positivi per i quali è stato emanato un provvedimenti di quarantena da asp

**Comment by gabacode** [comment]
> Buongiorno a tutti/e, nel form per il data entry avevo predisposto un campo per inserire le persone **attualmente in quarantena*** ma nello schema dati concordato con @gabacode non se ne fa riferimento. Procedo all'eliminazione del campo "quarantena" dal form oppure pensate possa essere un'informazione importante che potremmo implementare nello schema dati?
> 
> ***attualmente in quarantena** = attualmente positivi in isolamento domiciliare + contatti stretti non positivi per i quali è stato emanato un provvedimenti di quarantena da asp

Credo che il numero delle persone attualmente in quarantena sia un dato importante, anche perchè nel nostro caso, sommato al ```totale_ospedalizzati```, risulta nel ```totale_positivi```.

Se questo dato è disponibile, come anche quello dei contatti stretti, credo sia opportuno metterlo, o per lo meno predisporre il campo, qualora il dato sia disponibile. Si potrebbe poi sottrarre il numero dei ```contatti_stretti``` per derivare il ```totale_positivi```

Nello schema che ho utilizzato per il Distretto39 c'è il campo ```isolamento_domiciliare```, è quello il campo che si riferisce ai pazienti attualmente in quarantena.

**Comment by dennisangemi** [comment]
Permettimi di fare qualche piccolo chiarimento (correggetemi se sbaglio)

`isolamento_domiciliare` = `totale_positivi` - `totale_ospedalizzati`
`quarantena` = `isolamento_domiciliare` + `contatti_stretti`

Nel form io vorrei chiedere ai sindaci (o chi per loro) il numero delle persone in quarantena (che non necessariamente coincide con il numero delle persone in isolamento domiciliare). Noi poi, se ci servono, facciamo tutti i calcoli del caso per derivare contatti stretti ecc.

**Comment by gabacode** [comment]
Si, ottima idea! Per me va benissimo

**Comment by dennisangemi** [comment]
È un problema se questo dato (attualmente in quarantena) viene visualizzato in dashboard ma non esiste una colonna apposita nel file csv che è possibile scaricare? 

Se la risposta è "sì" proporrei una delle due soluzioni:
- rimuovere il campo "attualmente in quarantena" dal google form
- aggiungere una colonna apposita allo schema dati che pubblichiamo

**Comment by gabacode** [comment]
@dennisangemi ci ho messo qualche giorno a valutare e capire bene la domanda.
A quanto ho capito, in ```isolamento_domiciliare``` vanno i pazienti positivi al test molecolare, mentre in ```quarantena``` vanno anche le persone che sono state in contatto con essi, ma non necessariamente sono positive.

Lo schema del DPC riporta solo i pazienti in isolamento, ma non c'è riferimento ai pazienti non positivi in quarantena (correggimi se sbaglio).

Quindi, anche se credo che il numero di contatti sia un dato importante, forse al DPC non la pensano allo stesso modo, e avranno i loro validi motivi. Il motivo per cui l'ASP39 non sta tenendo conto dei contatti è perchè nel sistema gestionale ci sono solo pazienti positivi al tampone molecolare.

Ritornando alla domanda:

> È un problema se questo dato (attualmente in quarantena) viene visualizzato in dashboard ma non esiste una colonna apposita nel file csv che è possibile scaricare?

A questo punto, a mio avviso, non è un problema se non esiste la colonna nel csv, qualora volessimo attenerci il più possibile allo schema del DPC.

**Comment by dennisangemi** [comment]
Call 05/05/2021: Rimuoviamo (momentaneamente) dal form il campo "quarantena" e manteniamo invariato lo schema dati di output
