### ISSUE TITLE
Contattaci in caso di problemi

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#11]
Credo sia necessario individuare i canali da mettere a disposizione delle amministrazioni comunali per contattare ODS nel caso in cui dovessero riscontrare difficoltà/problemi.

Io avevo pensato:

- Email opendatasicilia@gmail.com
- gform in cui chiediamo email mittente e testo richiesta

Secondo me un form potrebbe essere più comodo perchè possiamo gestire le richieste delle amministrazioni e possiamo gestire le autorizzazioni dei membri di ODS che possono accedere alle risposte del form. 

Che ne dite?

**Comment by gpirrotta** [comment]
Secondo me va bene il Google Form, sia per questioni di semplicità sia per questioni di collaborazione.

**Comment by aborruso** [comment]
A mio avviso dovremmo fare in modo di veicolare il più possibile le richieste in pubblico. Proprio per l'anima del progetto, proprio per fare in modo che altri possano apprendere da esigenze già emerse.

E penso a questo https://github.com/opendatasicilia/informa-covid19/discussions/4

**Comment by gpirrotta** [comment]
> A mio avviso dovremmo fare in modo di veicolare il più possibile le richieste in pubblico. Proprio per l'anima del progetto, proprio per fare in modo che altri possano apprendere da esigenze già emerse.
> 
> E penso a [questo](https://github.com/opendatasicilia/informa-covid19/discussions/4)

Non conosco le discussions però mi piace l'idea. 
Una domanda: per partecipare la registrazione è obbligatoria vero?

**Comment by aborruso** [comment]
> Una domanda: per partecipare la registrazione è obbligatoria vero?

Sì. Ormai non c'è quasi più nessuno spazio che si può usare senza un account.

**Comment by dennisangemi** [comment]
Bellissimo! Allora aggiudicato discussion come canale preferenziale per segnalazioni/problemi?

**Comment by gpirrotta** [comment]
Sì, accendiamola!
