### ISSUE TITLE
gsheet --> github

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#13]
Dopo aver raccolto i csv dei comuni, potremmo creare repo github in cui pubblicare tutti questi dati. Chi si potrebbe occupare dell'automazione di questo punto?

**Comment by aborruso** [comment]
Chiudo, è stato impostato il lavoro qui:

https://github.com/opendatasicilia/informa-covid19/blob/main/script/informacovid/README.md
