### ISSUE TITLE
definire schema anagrafica CSV comuni

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/informa-covid19#14]
Faccio riferimento all'anagrafica di tutti i CSV, dei dati dei comuni che hanno aderito.

Una volta definito questo, mi posso occupare della #13.

Lo schema potrebbe essere

```yaml
- comune_codice_istat: 082053
  URL_csv: https:/ciao.it/bau
```

**Comment by dennisangemi** [comment]
Grazie mille, mi sembra ottimo. Quindi nell'ordine dovremmo fare: #12 --> #14 --> #13

**Comment by dennisangemi** [comment]
> Faccio riferimento all'anagrafica di tutti i CSV, dei dati dei comuni che hanno aderito.
> 
> Una volta definito questo, mi posso occupare della #13.
> 
> Lo schema potrebbe essere
> 
> ```yaml
> - comune_codice_istat: 082053
>   URL_csv: https:/ciao.it/bau
> ```

Ho ricordato solo adesso che avevo iniziato a fare un file del genere. Ti ho reso editor. Questo il link aperto ai commenti -->https://docs.google.com/spreadsheets/d/1eaKiVQhifRZpxqLh2vUCk4F7vm3nNP9nz67GrzArqtI/edit?usp=sharing

**Comment by aborruso** [comment]
Chiudo. Perché questa parte è stata implementata  https://github.com/opendatasicilia/informa-covid19/blob/main/script/informacovid/README.md
