### ISSUE TITLE
Definire licenza progetto

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/informa-covid19#16]
Come suggerito da @angelogulina [qui](https://github.com/opendatasicilia/informa-covid19/issues/15#issuecomment-830113150).

Essenzialmente stiamo costruendo una sorta di manuale, una procedura. Sarei portato a pensare una CC-BY per tutto.

Poi se scriviamo dei pezzi di codice "importante", scegliamo per questa parte delle licenze più adatte al codice sorgente.

My 2 cents

**Comment by gpirrotta** [comment]
4770e62e7e8b6a8f8b548eb081d0dfb20b1a2f6a

Ho aggiunto la CC-BY 4.0 al Readme 
Chiudo l'issue, in caso si riapre se c'è da discutere sulla licenza per il codice.

**Comment by aborruso** [comment]
Ho aggiunto il file di licenza anche nella root

![image](https://user-images.githubusercontent.com/30607/116733051-e6d41700-a9eb-11eb-9892-3be5b32e4772.png)
