### ISSUE TITLE
Dominio terzo livello

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/informa-covid19#19]
Ciao, 
lascio a voi la proposta di URL.

Io mi occupo soltanto di farla puntare qui.

**Comment by dennisangemi** [comment]
https://informacovid.opendatasicilia.it/ ?

**Comment by gpirrotta** [comment]
> https://informacovid.opendatasicilia.it/ ?

Per me va bene

**Comment by dennisangemi** [comment]
> Potrebbe essere una buona idea far partire i redirect alle dashboard da tale dominio? In questo modo potremmo anche mettere uno script per il redirect a diverse dashboard, in caso di desktop, o mobile. Con un framework tipo Next.js of Gatsby si potrebbero generare url dinamici per n comuni. (es. [https://informacovid.opendatasicilia.it/dashboard/[comune].js](https://informacovid.opendatasicilia.it/dashboard/%5Bcomune%5D.js))

bello, bellissimo, figo, fighissimo, facciamolo vi prego

**Comment by aborruso** [comment]
Attivato https://informacovid.opendatasicilia.it/
