### ISSUE TITLE
Definizione tracciato record file di output comuni CSV

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#22]
Buongiorno! Prendendo spunto dal [tracciato record del dpc](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md) e dallo schema dati proposto da gaba ho provato a definire il nostro tracciato record in [questo file](https://docs.google.com/spreadsheets/d/1ZLpChVxtdbeuyAkMn_0pxNzhxKjFZ4kp9K098QalOjI/edit?usp=sharing)

**Comment by aborruso** [comment]
È stato definito qui https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/informacovid_schema.yaml

Il file è sia human readable, che machine readable (viene letto da un sistema di controllo, e verifica che i file siano compatibili)
