### ISSUE TITLE
Element Open graph per landing Page

### ISSUE THREAD

**Issue by angelogulina** [opendatasicilia/informa-covid19#24]
Per far sì che, quando si condivide il progetto, si abbia una preview/contesto sui vari social, bisogna:

- predisporre le card per i vari social
- aggiungere i tag Open Graph per i vari social

**Comment by aborruso** [comment]
@angelogulina la preview su [twitter](https://cards-dev.twitter.com/validator) non mi sembra rispondere bene,

Non so se ci siano ancora lavori in corso.



![image](https://user-images.githubusercontent.com/30607/117129141-9ddee280-ad9e-11eb-8dcc-d520d55e9763.png)

**Comment by dennisangemi** [comment]
Se serve una mano per la grafica delle card sapete dove trovarmi ;)

**Comment by angelogulina** [comment]
@aborruso grazie.

Credo la Issue sia stata chiusa automaticamente con il Merge 🤔 la riapro.
La card di Twitter pare richiedere il path assoluto, @gabacode lo sta sistemando e facciamo un nuovo deploy subito dopo.

@dennisangemi le Social card ce le ho [qui](https://github.com/opendatasicilia/informa-covid19/tree/main/src/assets). Se vuoi dare un parere, sentiti libero.

**Comment by dennisangemi** [comment]
Scusami @angelogulina , pensavo non fossero ancora pronte. Sono perfette così. Grazie

**Comment by angelogulina** [comment]
No problem @dennisangemi 🎉 

Al prossimo deploy invece, vedrai le tue card per le dashboard in tutto i loto splendore 🤞

**Comment by gabacode** [comment]
![Screenshot_20210505_134541](https://user-images.githubusercontent.com/38985346/117136139-404f9380-ada8-11eb-944d-c7aa1e2189a1.png)
Dovrebbe andare adesso

**Comment by angelogulina** [comment]
MA CHE BELLA GRAFICA OH 😂 chiudo Issue
