### ISSUE TITLE
Modificare ordine colonne elenco-comuni-italiani.csv

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#29]
In gsheet, quando uso vlookup per attingere tutte le info dal file [elenco-comuni-italiani.csv ](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/dati-popolazione/elenco-comuni-italiani.csv) , è necessario (se non sbaglio) che la prima colonna sia "comune_denominazione".

Che ne dite di modificare l'ordine delle colonne del CSV preparato da @gabacode come di seguito?

comune_denominazione
comune_codice_istat
latitudine
longitudine
popolazione
provincia_denominazione
provincia_sigla
regione_denominazione
regione_codice

(o qualsiasi altra configurazione nella quale la colonna "comune_denominazione" sia la prima)

**Comment by aborruso** [comment]
Per me è ok.

**Comment by gabacode** [comment]
Perfetto, procedo al reindex!
