### ISSUE TITLE
Comuni "doppioni" e menu a tendina

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/informa-covid19#30]
Ho notato che in Italia esistono 5 Comuni "doppioni", cioè aventi lo stesso ```comune_denominazione``` ma facenti parte di Regioni diverse.

I Comuni in questione sono (```comune, province```):

- Calliano (AT, TN)
- Livo (CO, TN)
- Peglio (PU, CO)
- Samone (TO, TN)
- San Teodoro (ME, SS)

Quando questi comuni sono cercati dal menu a tendina, solo uno viene ritornato. E' possibile ritornare una query che invece di ```comune_denominazione``` mostri il formato ```comune_denominazione (provincia_sigla)``` ? (es. San Teodoro (ME))

**Comment by aborruso** [comment]
Ciao @gabacode non mi occupo io della cosa. Lascio a @dennisangemi 

Se ci sono difficoltà, do una mano volentieri

**Comment by gpirrotta** [comment]
Ho creato la colonna `comune_denominazione_e_provincia` con la formula `=CONCATENATE(A2;" (";G2;")")` e aggiornato l'intervallo di validazione. Se il CSV di partenza rimane fisso come numero di colonne penso potrebbe andare bene così, al più la colonna potrebbe essere creata dopo un po' di colonne vuote, per lasciare un po' di spazio `fittabile` da eventuali nuove colonne del CSV. 
Ho visto che è possibile validare anche chiamando una formula. @aborruso sai se è possibile combinare la validazione per elenco e formula, in modo da evitare di creare la nuova colonna?

[foglio](https://docs.google.com/spreadsheets/d/19CDsgmt68JQ3NbDiZar9IaAh6kMI2V5i9d5hwbHzCWA/edit#gid=2027416371)

**Comment by dennisangemi** [comment]
Mi sembra perfetto! Grazie mille Gio. Ho modificato alcuni riferimenti alle celle e spostato la colonna che hai creato in modo tale da renderla prima colonna. 

p.s.
se @aborruso fa qualche magheggio per evitare la creazione di una nuova colonna gli siamo grati ma così credo che funzioni tutto

**Comment by gpirrotta** [comment]
Ottimo @dennisangemi, hai spostato la nuova colonna come prima colonna. In questo modo non c'è il pericolo con eventuali nuovi campi del CSV. Io non l'avevo fatto perché non volevo spostare la posizione originale delle colonne e modificare magari il comportamento del foglio stesso.

**Comment by dennisangemi** [comment]
Grazie mille, se è tutto ok possiamo chiudere issue

**Comment by aborruso** [comment]
chiuderei :)

**Comment by dennisangemi** [comment]
Grazie a tutti ;) 

p.s. mi piace un sacco chiudere issue haha
