### ISSUE TITLE
validazione dati comuni

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/informa-covid19#32]
Ciao,
ho implementato una prima validazione, a partire dalla prima anagrafica di esempio, fatta da due comuni:

<https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/informacovid.yml>

La validazione confronta i CSV con [questo schema dati](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/informacovid_schema.yaml) e li "marca" come validi e invalidi.

Qui il [report](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/report.csv). Il comune `086006` non è valido, perché ha la colonna `distretto` e non `sigla_provincia`.

@dennisangemi è normale che sia così?

**Comment by dennisangemi** [comment]
Buongiorno e grazie @aborruso ,
temo di averti comunicato il link sbagliato (e mi scuso).

Il link corretto per il csv del comune di catenanuova è --> https://docs.google.com/spreadsheets/d/e/2PACX-1vTlrE5ZIN7G8gH1liZwmwP0HCsw9YSrxHF_ccpHIGXVJRBsyCvtpinRBLLjbM8Au_BoGaqxLdZeDB59/pub?gid=234868662&single=true&output=csv

**Comment by aborruso** [comment]
@dennisangemi con l'URL che mi hai dato, la validazione è ok anche per `086006` https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/report.csv
