### ISSUE TITLE
Collegare anagrafica comuni a gsheet

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#33]
Collegare la nuova anagrafica comuni agli sheet di:

- [x] Regalbuto
- [x] Catenanuova
- [x] Serradifalco
- [x] Calascibetta
- [x] Villarosa

- [x] formattare codice ISTAT "000000"

**Comment by aborruso** [comment]
Dennis, solo per dirti che puoi farlo da solo, modificando il file di anagrafica.

È in formato yaml. 

In questo formato, gli "spazietti" di indentazione che trovi, non sono soltanto un fatto visuale, quindi c'è da farci attenzione.

**Comment by aborruso** [comment]
@dennisangemi aggiungo una nota: ho inserito un altro controllo di validazione: il codice comune deve essere espresso come `000000`.

E adesso ad esempio non è più valido `086016`, perché lì il codice comune non è espresso come numero.

**Comment by dennisangemi** [comment]
Grazie @aborruso , credo di essermi espresso male. Ho creato issue solo per ricordarmi di importare l'elenco comuni italiani di gaba in alcuni sheet già esistenti. 

Per quanto riguarda la modifica del file yaml, posso provarci ma ho paura di "fare danno" ;)

**Comment by dennisangemi** [comment]
Importando l'elenco comuni italiani di gaba negli sheet sopra citati, risolviamo anche il problema del 000000

**Comment by aborruso** [comment]
> Per quanto riguarda la modifica del file yaml, posso provarci ma ho paura di "fare danno" ;)

Appena hai una lista di URL che consideri definitivi, assegnami per favore la issue "aggiornare anagrafica comuni", indicandomi dove trovare questa lista.

Grazie

**Comment by dennisangemi** [comment]
> @dennisangemi aggiungo una nota: ho inserito un altro controllo di validazione: il codice comune deve essere espresso come `000000`.
> E adesso ad esempio non è più valido `086016`, perché lì il codice comune non è espresso come numero.

Ho aggiornato lo sheet di Regalbuto (086016). @aborruso per favore, appena puoi, verifichi che il campo codice comune rispetti la formattazione scelta? grazie ;)

**Comment by aborruso** [comment]
Caro @dennisangemi ogni giorno, intorno alle 18:15 (l'orario lo potremo cambiare) vengono aggiornati i dati e in parallelo fatto il check.

Aspetterei la magia dell'automatismo e vedremo qui gli esiti :) https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/report.csv

**Comment by dennisangemi** [comment]
Grazie! Non avevo capito il check venisse fatto ogni giorno.

**Comment by aborruso** [comment]
> Grazie! Non avevo capito il check venisse fatto ogni giorno.

Viene eseguito secondo i parametri scritti qui https://github.com/opendatasicilia/informa-covid19/blob/main/.github/workflows/informacovid.yml#L7

`45 15 * * *`, sono minuti, ora, giorno del mese, mese, giorno della settimana, secondo le specifiche dell'utility di pianificazione denominata `cron`.

Qui sono impostati soltanto minuti e ora, quindi vuol dire ogni giorno alle 15:45. secondo l'orario dei server GitHub, che è UTC; quindi sarebbero le nostre 17:45. 
Ma non parte in orario, è free, c'è traffico, l'Etna, ecc., e di solito c'è da aspettare 15/30 minuti.

**Comment by gabacode** [comment]
Scusate se è OT: @aborruso posso aggiungere i comuni di Bagheria, e i relativi .csv al file ```informacovid.yml``` ?

**Comment by aborruso** [comment]
> Scusate se è OT: @aborruso posso aggiungere i comuni di Bagheria, e i relativi .csv al file `informacovid.yml` ?

Non è OT. 

Certo

**Comment by aborruso** [comment]
> Ho aggiornato lo sheet di Regalbuto (086016). @aborruso per favore, appena puoi, verifichi che il campo codice comune rispetti la formattazione scelta? grazie ;)

Ancora il CSV ha il codice comune numerico. L'URL che uso, e che ho letto giorni fa dallo sheet che mi hai condiviso è questo:

https://docs.google.com/spreadsheets/d/e/2PACX-1vRXHbLv9Jm42EA8Y3YExNUUwKJkRTkrtQklpbnRjWI6IjqDyd6Qz6qg2vMpYQa6gTfS47qgzP0GnpuM/pub?output=csv

**Comment by dennisangemi** [comment]
Il link è corretto e ho inserito formattazione 000000 alla cella collegata al file di @gabacode  (Formato --> Numero --> Altri formati --> 000000). Se al prossimo check (domani) viene rilevato un altro errore, cerco un'altra soluzione. Che dici?

**Comment by aborruso** [comment]
> Il link è corretto e ho inserito formattazione 000000 alla cella collegata al file di @gabacode (Formato --> Numero --> Altri formati --> 000000). Se al prossimo check (domani) viene rilevato un altro errore, cerco un'altra soluzione. Che dici?

Con le modifiche che hai fatto, adesso è ok https://github.com/opendatasicilia/informa-covid19/commit/ae758c313ed66f02413bbfdcfe123ec26a9fb022

**Comment by dennisangemi** [comment]
Grazie mille, allora chiudo questa issue e apro "aggiornare anagrafica comuni".

**Comment by aborruso** [comment]
@gabacode sembra ok
https://github.com/opendatasicilia/informa-covid19/tree/main/dati/informacovid
