### ISSUE TITLE
Aggiornare anagrafica comuni

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#34]
In [questo sheet ](https://docs.google.com/spreadsheets/d/1eaKiVQhifRZpxqLh2vUCk4F7vm3nNP9nz67GrzArqtI/edit?usp=sharing) ho raccolto i csv di output dei comuni (ho verificato tutti i link in modo tale da non avere problemi).

Ho creato anche una colonna "yml" per avere un quadro chiaro dei comuni da inserire e quelli già inseriti.

Grazie mille per tutto ;)

**Comment by aborruso** [comment]
Sembra tutto ok

https://github.com/opendatasicilia/informa-covid19/tree/main/dati/informacovid

**Comment by aborruso** [comment]
Non avevo capito, devo inserire quelli in rosso credo.

Riapro

**Comment by aborruso** [comment]
@dennisangemi perché nella colonna link CSV, due non sono link a CSV?

Che URL devo mettere per questi due?

Grazie

![image](https://user-images.githubusercontent.com/30607/117058137-8d872300-ad1e-11eb-8c6a-068ce9a1d5c2.png)

**Comment by dennisangemi** [comment]
Perdonami @aborruso . Questi link diventeranno il mio incubo. Ho corretto il file (spero definitivamente).

Qui i link:
- Calascibetta --> https://docs.google.com/spreadsheets/d/e/2PACX-1vRXnUM3MzQFHGuubIWljU74Bu5RxxsKuQU8mFjMMjCYB2PFhb1zBsZ5PXbFxqP9eLOSP39SIP8TPLTd/pub?gid=1312444582&single=true&output=csv
- Villarosa --> https://docs.google.com/spreadsheets/d/e/2PACX-1vRXnUM3MzQFHGuubIWljU74Bu5RxxsKuQU8mFjMMjCYB2PFhb1zBsZ5PXbFxqP9eLOSP39SIP8TPLTd/pub?gid=1116770854&single=true&output=csv

**Comment by aborruso** [comment]
@dennisangemi hanno dei problemi, guarda lat e long qui

![image](https://user-images.githubusercontent.com/30607/117059653-53b71c00-ad20-11eb-86e3-df8b7740b58c.png)

**Comment by dennisangemi** [comment]
Purtroppo gsheet quando importa il csv di @gabacode decide di cambiare completamente (?) i campi lat e long. Abbiamo provato a cercare in rete una soluzione ma ci stiamo per arrendere. Domani apro issue qui con la speranza che possiate aiutarci. 

[Qui ](https://docs.google.com/spreadsheets/d/19CDsgmt68JQ3NbDiZar9IaAh6kMI2V5i9d5hwbHzCWA/edit?usp=sharing)il template di gsheet. Il problema è nel foglio anagrafica_comuni.
