### ISSUE TITLE
Importate CSV con decimali all'inglese

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/informa-covid19#35]
Purtroppo gsheet quando importa il csv di @gabacode decide di cambiare completamente (?) i campi lat e long. Abbiamo provato a cercare in rete una soluzione ma ci stiamo per arrendere. Domani apro issue qui con la speranza che possiate aiutarci. 

[Qui ](https://docs.google.com/spreadsheets/d/19CDsgmt68JQ3NbDiZar9IaAh6kMI2V5i9d5hwbHzCWA/edit?usp=sharing)il template di gsheet. Il problema è nel foglio anagrafica_comuni.

_Originally posted by @dennisangemi in https://github.com/opendatasicilia/informa-covid19/issues/34#issuecomment-832193400_

**Comment by aborruso** [comment]
@dennisangemi mi scrivi, solo per conferma, l'URL del CSV che dovete importare?

**Comment by dennisangemi** [comment]
https://raw.githubusercontent.com/opendatasicilia/informa-covid19/main/dati/dati-popolazione/elenco-comuni-italiani.csv

**Comment by aborruso** [comment]
ciao @dennisangemi avete diverse soluzioni. 

La più facile è quella di usare gli sheet con impostazione all'inglese. Io lo faccio di default, perché nel mondo dei dati i decimali sono quasi sempre in quel modo. Va in file, impostazioni sheet e lo imposti così

![image](https://user-images.githubusercontent.com/30607/117063658-6a13a680-ad25-11eb-97e9-6d547bfd7216.png)


Oppure rimani all'italiana, cancelli la formattazione, imposti tutto a plain text e usi uno script di import come quello di sotto-
[Qui](https://docs.google.com/spreadsheets/d/16X16J_YfBYifqv9b_smiNlT7TcrXQGNErOVmrGH3y2M/edit?usp=sharing) lo trovi applicato.

![image](https://user-images.githubusercontent.com/30607/117063709-7dbf0d00-ad25-11eb-904c-7e27347dff73.png)

![image](https://user-images.githubusercontent.com/30607/117063993-dee6e080-ad25-11eb-9c6d-81e3352f120a.png)



```javascript
function importCSVFromWeb() {

  // Provide the full URL of the CSV file.
  
  // nota bene il CSV sorgente non deve avere \n e/o \r
  var csvUrl = "https://raw.githubusercontent.com/opendatasicilia/informa-covid19/main/dati/dati-popolazione/elenco-comuni-italiani.csv";
  var csvContent = UrlFetchApp.fetch(csvUrl).getContentText();
  //csvContent.replace(/[ \t]+$/gm, ' ');
  var csvData = Utilities.parseCsv(csvContent);
  
  var sheet = SpreadsheetApp.getActiveSheet();
  var sheet = SpreadsheetApp.getActive().getSheetByName('Sheet1')
  sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);

}
```

**Comment by dennisangemi** [comment]
Ma come faremmo senza di te? <3

in inglese funziona tutto perfettamente. Ho provato anche a duplicare il file con un altro account e come dice @gabacode "si tira i settings". Ottimo. Grazie mille @aborruso
