### ISSUE TITLE
Aggiornare popolazione a dati ISTAT 2021

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/informa-covid19#38]
E' uscito il [nuovo file](http://demo.istat.it/pop2021/dati/comuni.zip) con i dati relativi alle popolazioni dei Comuni italiani nel 2021.

A quanto pare i nuovi dati sono già utilizzati da ieri come denominatore per il calcolo dell'indice 250 (ma non ho trovato la direttiva ministeriale)

Da aggiornare lo script e il file ```elenco-comuni-italiani.csv```

ps non ci sono ancora dati rispettivi alla popolazione di Misiliscemi, gli altri Comuni che erano mancanti in ISTAT2020 sono stati invece aggiunti.

**Comment by pigreco** [comment]
Che brutto CSV, siamo alle solite.

NB. il valore `999` nel campo `Età`  (se non erro) equivale al totale popolazione per comune.

**Comment by gabacode** [comment]
> Che brutto CSV, siamo alle solite.
>
Si, non è il massimo..però per quest'anno hanno almeno cancellato le ultime due righe del foglio, il che facilita il compito dello script, sperando che tengano lo stesso format nei prossimi anni.

> NB. il valore `999` nel campo `Età` (se non erro) equivale al totale popolazione per comune.
>
Si, lo [script](https://github.com/opendatasicilia/informa-covid19/blob/f90534b1dd2b3558621234612d185148140a8162/script/dati-popolazione/2_popolazione.py#L30-L31) somma le colonne `Totale Maschi` e  `Totale Femmine` nell'ultima riga (età `999`) di ogni comune, per derivare i totali. Finchè i dati rimarranno coerenti, dovrebbe continuare a funzionare.
