### ISSUE TITLE
Immissione errata dei dati nel form

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/informa-covid19#39]
Cosa fare se il sindaco inserisce per errore un dato sbagliato nel form?

Se il sindaco sbaglia si può chiedere di inserire nuovamente il dato corretto ma bisognerebbe dare anche le indicazioni per entrare nel foglio e rimuovere la riga sbagliata. Che ne pensi @dennisangemi ?

In ogni caso lo scenario va documentato sia nel tutorial PDF sia nel video.

**Comment by dennisangemi** [comment]
È possibile rettificare l'errore tramite lo stesso Google Form per evitare che si modifichino le celle dello sheet. Dopo l'invio del modulo si potrà decidere se "Modificare la risposta" o inviarne un'alta come di seguito![Screenshot_20210505-224659_Chrome.jpg](https://user-images.githubusercontent.com/77018886/117207306-1d4ad100-adf4-11eb-9ebd-8c079009b215.jpg)

**Comment by gpirrotta** [comment]
Ottimo, documentiamo tutto nel tutorial/video.
