### ISSUE TITLE
Servizio redirect per Dashboards desktop e mobile

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/informa-covid19#42]
Come accennato in precedenza e su #12 :

> Pensavo di chiedere anche i link alle dashboard a seguito della proposta fatta da @gabacode (ovvero creare dei collegamenti che da informacovid.opendatasicilia.it permettano di aprire le dashboard dei singoli comuni, correggimi se sbaglio)

_Originally posted by @dennisangemi in https://github.com/opendatasicilia/informa-covid19/issues/12#issuecomment-832905517_

E' possibile generare URLs redirect dinamici a seconda del dispositivo dal quale si sta accedendo alla pagina. Questo per ovviare alla presenza di doppi link, per desktop e mobile, e facilitare l'accesso a tutte le Dashboard disponibili, da un unico servizio redirect.
(es. https://informacovid.opendatasicilia.it/dashboard/regalbuto)

Si potrebbe poi fetchare un .CSV o altra API che contenga le proprietà ad esempio:

- comune: 'Nome del Comune',
- desktop: 'URL_datastudio_desktop',
- mobile: 'URL_datastudio_mobile

Ad ogni nuovo deploy, Svelte fetcha il nuovo file, genera l'URL, e redirecta alle versioni desktop, o mobile, a seconda del dispositivo utilizzato. Così si eviterebbe anche di dover registrare un bit.ly (o analogo) per ogni comune, e l'indirizzo verrebbe aggiornato semi-automaticamente ad ogni deploy.

L'unico passo sarebbe quello di condividere gli URL alle dashboards tramite Google Form da parte dei Comuni, aggiornare il CSV e re-deployare l'app.

**Comment by dennisangemi** [comment]
> Si potrebbe poi fetchare un .CSV o altra API che contenga le proprietà ad esempio:
> 
> * comune: 'Nome del Comune',
> * desktop: 'URL_datastudio_desktop',
> * mobile: 'URL_datastudio_mobile

Ecco il CSV (dinamico)

https://docs.google.com/spreadsheets/d/e/2PACX-1vTBh0KSnQZ3GWbgflngzpkiEVizEtbjZFuxFilEp24Vi0fhzV8saDb84FmTh7hOCTW78oKuTmvm52LF/pub?gid=1801149498&single=true&output=csv

**Comment by gabacode** [comment]
Funziona, aggiornando [questo file](https://github.com/opendatasicilia/informa-covid19/blob/main/src/routes/d/_comuni.js).
Al momento, chiudo.
