### ISSUE TITLE
Pubblicare videotutorial su YouTube

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#44]
Grazie mille @aborruso , qui il link al video e le info utili per la pubblicazione

Video --> https://drive.google.com/file/d/1zwwGclkCoLzUeNq6evvOsaxJWmtkjdag/view?usp=sharing

Titolo
InformaCOVID, il Kit di Comunicazione Efficace per il tuo Comune

Descrizione

InformaCovid è una cassetta degli attrezzi contenente strumenti digitali "gratuiti", che proponiamo a tutti i comuni che vorranno aderire alla nostra iniziativa per fornire alla propria comunità un'informazione puntuale e di qualità. La cittadinanza avrà a disposizione una dashboard interattiva, aggiornata dinamicamente, attraverso cui visualizzare l'andamento dei contagi della propria città tramite PC, tablet e dispositivo mobile

Come funziona?
La soluzione che proponiamo utilizza strumenti gratuiti disponibili in rete, in pochi semplici passaggi la piattaforma è disponibile e pronta per essere utilizzata. I servizi su cui si basa la soluzione proposta sono gratuiti e disponibili in rete.

A chi è rivolto?
InformaCovid è rivolto principalmente ai sindaci delle città italiane, ma non solo. Associazioni, scuole, testate giornalistiche, praticamente chiunque sia in possesso di dati COVID19, provenienti da fonti ufficiali ed autorevoli, può utilizzare la piattaforma per dare comunicazione alla cittadinanza.

Chi siamo
Siamo la comunità Open Data Sicilia, da anni impegnata a diffondere la cultura dell'open government e le prassi dell'open data nel nostro territorio siciliano. Siamo accomunati dalla genuina volontà di contribuire a migliorare la qualità della vita delle nostre comunità e vogliamo farlo con spirito di collaborazione e concretezza.

Contattaci
Ricordiamo che InformaCovid è un prodotto gratuito e che noi, come comunità, non vendiamo né servizi né consulenze. Tuttavia, per qualsiasi dubbio, chiarimento e/o supporto (sempre gratuito), non esitate a contattarci. Come comunità saremo lieti di potervi dare il nostro aiuto. Il sito di riferimento del progetto è https://informacovid.opendatasicilia.it

**Comment by aborruso** [comment]
ciao @dennisangemi c'è una copertina?

**Comment by dennisangemi** [comment]
Eccola https://drive.google.com/file/d/1xLlrS1FyO23GLnQpVUDKmE1gxkXFCW_s/view?usp=sharing scusami

**Comment by dennisangemi** [comment]
> Eccolo qui, per il momento "unlisted" https://www.youtube.com/watch?v=gVvy9KQune0

Grazie mille

**Comment by aborruso** [comment]
> Eccola https://drive.google.com/file/d/1xLlrS1FyO23GLnQpVUDKmE1gxkXFCW_s/view?usp=sharing scusami

Fatto, grazie a te.

Se per te è ok, chiudi
