### ISSUE TITLE
Inserimento immagine dashboard in homepage

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/informa-covid19#47]
Ciao a tutti,
mi piacerebbe fosse presente da qualche parte in homepage l'immagine della dashboard completa. 

![image](https://user-images.githubusercontent.com/2639616/117998107-e02a9580-b343-11eb-84f6-e10d877eb938.png)

Che ne pensate? 
@dennisangemi @angelogulina @gabacode @aborruso

**Comment by aborruso** [comment]
Per me ok.

Metterei qui sotto

![image](https://user-images.githubusercontent.com/30607/117999101-cf2e5400-b344-11eb-89d3-db3aa3116af4.png)

**Comment by angelogulina** [comment]
@gpirrotta _ceci n'est pas une dashboard_ 😄 

La dashboard completa è un po' vaga forse com idea? Quale dashboard? Di quale comune e con quali dati? Non trovi sufficiente il fatto che sia velocemente raggiungibile da link?

**Comment by gpirrotta** [comment]
> @gpirrotta _ceci n'est pas une dashboard_ 😄
 😄😄😄😄
![image](https://user-images.githubusercontent.com/2639616/118014274-4ec31f80-b353-11eb-9cae-ea86f87ed8b4.png)


> La dashboard completa è un po' vaga forse com idea? Quale dashboard? Di quale comune e con quali dati? Non trovi sufficiente il fatto che sia velocemente raggiungibile da link?

Secondo me la persona che si collega, per essere più invogliato, dovrebbe vedere nella landing già il risultato finale della dashboard (e forse anche del BOT). Come città secondo me Regalbuto è rappresentativa.

my2c

**Comment by gpirrotta** [comment]
> Per me ok.
> 
> Metterei qui sotto
> 
> ![image](https://user-images.githubusercontent.com/30607/117999101-cf2e5400-b344-11eb-89d3-db3aa3116af4.png)

Stavo pensando Andrea, che ne pensi se inseriamo una nuova sezione chiamata **InformCOVID**  con sotto gli screenshot sia della dashboard che del BOT?

**Comment by aborruso** [comment]
> Stavo pensando Andrea, che ne pensi se inseriamo una nuova sezione chiamata **InformCOVID** con sotto gli screenshot sia della dashboard che del BOT?

Gio, sono d'accordo anche il bot si deve "vedere", deve essere chiaro da subito che esiste.

**Comment by angelogulina** [comment]
Direi allora di fare così, queste due sezioni le inseriamo in una pagina diversa. Così disposte mi sembra prendano troppo spazio per comunicare qualcosa di importante ma che non dovrebbe essere impaginato così probabilmente.

<img width="1024" alt="Screenshot 2021-05-13 at 10 19 34" src="https://user-images.githubusercontent.com/4223655/118098879-c5543180-b3d4-11eb-8d29-582f7f769949.png">

Aggiungiamo una sezione dei prodotti: dashboard e bot.

Permettetemi di mettere il _cappello da grafico_ e consigliarvi: solo lo screenshot della dashboard è molto triste. Sarebbe meglio averla piazzata su un desktop _à la_ @dennisangemi. A questo punto il problema è che duplica la sezione _esperienze_.

Proposta: mettiamo solo i loghi dei Comuni che hanno già aderito (e aderiranno) nella sezione esperienze. Usiamo i piazzamenti su device sia per la Dashboard che per il bot (anche questo piazzato dentro uno smartphone).

Che ne dici @gpirrotta? @dennisangemi potresti occuparti dei piazzamentI?

**Comment by angelogulina** [comment]
(Aggiungo una nota: noi proponiamo un kit che in quanto tale comprende dei prodotti ma l'idea di partenza era anche di fornire delle buone pratiche, cosa che alla fine esula dagli strumenti specifici che forniamo (ad es: se un Comune vuole farsi la dashboard con Flourish, poco importa, basta che siano implementate le pratiche che noi suggeriamo).

Mettere i prodotti al centro secondo me sposta un po' il tenore della comunicazione. Cosa che non è un difetto ma volevo solo farlo notare).

**Comment by gpirrotta** [comment]
> Proposta: mettiamo solo i loghi dei Comuni che hanno già aderito (e aderiranno) nella sezione esperienze. Usiamo i piazzamenti su device sia per la Dashboard che per il bot (anche questo piazzato dentro uno smartphone).
> 
> Che ne dici @gpirrotta? @dennisangemi potresti occuparti dei piazzamentI?

Sono d'accordo!

**Comment by gpirrotta** [comment]
> (Aggiungo una nota: noi proponiamo un kit che in quanto tale comprende dei prodotti ma l'idea di partenza era anche di fornire delle buone pratiche, cosa che alla fine esula dagli strumenti specifici che forniamo (ad es: se un Comune vuole farsi la dashboard con Flourish, poco importa, basta che siano implementate le pratiche che noi suggeriamo).
> 
> Mettere i prodotti al centro secondo me sposta un po' il tenore della comunicazione. Cosa che non è un difetto ma volevo solo farlo notare).

Hai ragione, l'idea è quella di fornire delle buone pratiche. Allo stesso tempo descriviamo un processo già di per sé fortemente brandizzato (perché non abbiamo scelto Office365 invece di Google Spreadsheet, ad esempio?). L'approccio che indichiamo è fortemente applicativo e secondo me è utile dare evidenza del prodotto finale ottenuto, anche se è fortemente Google oriented, che per inciso, non mi fa impazzire sponsorizzare. 
Inserire gli screenshot (come suggerisci bene tu piazzati dentro un device) direttamente sulla landing potrebbe far scattare all'utente quell'effetto **WOW** che magari potrebbe incuriosirlo e portarlo ad approfondire l'argomento. Secondo me è un compromesso accettabile ( _in medio stat virtus_  🙂  ).
Ben vengano queste note, mi aiutano a riflettere su aspetti non considerati e mi costringono a tenere presente prospettive d'insieme.

**Comment by dennisangemi** [comment]
> Proposta: mettiamo solo i loghi dei Comuni che hanno già aderito (e aderiranno) nella sezione esperienze. Usiamo i piazzamenti su device sia per la Dashboard che per il bot (anche questo piazzato dentro uno smartphone).
> 
> Che ne dici @gpirrotta? @dennisangemi potresti occuparti dei piazzamentI?

D'accordissimo su tutto. Entro il weekend ti faccio avere i files ;)

**Comment by angelogulina** [comment]
@gpirrotta ho inserito quanto detto sopra. Servirebbero di brevi testi da inserire qui, al posto dei placeholder. Il posizionamento si è reso necessario per rendere la pagina più armonica. Una volta che il deploy è fatto, puoi vedere come sembra.

<img width="974" alt="Screenshot 2021-05-18 at 13 36 11" src="https://user-images.githubusercontent.com/4223655/118647316-7dbd1380-b7e1-11eb-9ab9-2e6e22f3bc74.png">

Grazie!

**Comment by gpirrotta** [comment]
@angelogulina 

Per la prima immagine:

_Con InformaCOVID potrai realizzare in pochi
semplici passi una dashboard 
completa, dinamica e interattiva attraverso cui
 monitorare, tramite grafici, curve e dati, 
l'andamento dei contagi COVID19 del proprio territorio._


Per la seconda immagine:

_CovidBOT è un BOT Telegram, cioè un risponditore
automatico che riusa i dati aperti
del progetto InformaCOVID e consente di interagire
con essi in modo facile e instantaneo attraverso
comandi inviati tramite messaggi via chat.
Il BOT è disponibile via Web, desktop e mobile 
ed è raggiungibile a questo [link](https://t.me/Covid_19_Sicilia_Bot)._

**Comment by angelogulina** [comment]
@gpirrotta ha sistemato questa con #50 – chiudo
