### ISSUE TITLE
Data di lancio

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/informa-covid19#48]
Ciao a tutti
abbiamo deciso di lanciare il progetto il **25 maggio alle 17:00** e di associare all'evento una presentazione live.

Per arrivare al meglio al giorno della presentazione è necessario:
 - [x] preparare il testo da inviare nella newsletter una settimana prima la data di lancio, quindi il 18 maggio
 - [x] preparare un blog post (possiamo riutilizzare il testo del punto precedente)
 - [x] preparare una card (si può utilizzare quella già fatta per YT) da usare per i social
 - [x] pianificare gli interventi e i tempi della presentazione live

**Comment by gpirrotta** [comment]
Ho scritto il testo per la newsletter da inviare giorno 18.
Potete dare una controllata/revisionata?

[Foglio](https://docs.google.com/document/d/1BwH4D6AGIVrDvtwnYhqcoIoi9HK67966saP-OIba3Cw/edit)

**Comment by pcmasuzzo** [comment]
@gpirrotta ho fatto un po' di modifiche in suggesting mode.

Alcuni pezzi mi sembravano poco scorrevoli, o ripetitivi.
Spero di aver fatto cosa buona.

**Comment by angelogulina** [comment]
Abbiamo concordato come dividere i lavoro con @dennisangemi – nel tardo pomeriggio, prima serata oggi _esco_ le social card e le metto in repo, da utilizzare per la condivisione. Baci.

**Comment by aborruso** [comment]
> abbiamo deciso di lanciare il progetto il 25 maggio e di associare all'evento una presentazione live.

A che ora?

**Comment by aborruso** [comment]
Mi ha chiamato @gpirrotta e mi ha detto alle 17:00. Ho modificato il suo post

**Comment by picomiles** [comment]
ho effettuato delle piccole rettifiche alla lettera d'invito.
Se si usa lo stesso testo per invitare i sindaci basta passare dal "tu" al "lei" che mi sembra più appropriato.
(si tratta di due sole modifiche, nella prima e nella penultima riga della lettera)

**Comment by gpirrotta** [comment]
> @gpirrotta ho fatto un po' di modifiche in suggesting mode.
> 
> Alcuni pezzi mi sembravano poco scorrevoli, o ripetitivi.
> Spero di aver fatto cosa buona.

Grazie Paola, adesso si legge molto meglio 👍

**Comment by aborruso** [comment]
@gpirrotta e tutte e tutti ecco l'evento programmato https://www.youtube.com/watch?v=ZSrQbeaOeF4

**Comment by angelogulina** [comment]
La card è caricata [qui](https://github.com/opendatasicilia/informa-covid19/blob/main/src/assets/social-card-preview.png) per chi volesse dare feedback. Grazie!

**Comment by pcmasuzzo** [comment]
@angelogulina la card è molto bella! 

Ci possiamo aggiungere il link all'evento? Se è un tiny-url, ovviamente. 
@aborruso - con il numero di persone iscritte al canale che ha superato 100, si può avere un link facile all'evento?
Se non serve, ignoratemi.

**Comment by aborruso** [comment]
> @aborruso - con il numero di persone iscritte al canale che ha superato 100, si può avere un link facile all'evento?

Sì, e ci provo da settimane, ma non è ancora abilitato :(
