### ISSUE TITLE
Sistemare link in dashboard

### ISSUE THREAD

**Issue by angelogulina** [opendatasicilia/informa-covid19#52]
**Descrivi il problema**

La sezione dashboard/covid bot ha un problema di allineamento testo.

**Cosa accade al momento?**

Il link non è allineato rispetto al testo

**Cosa dovrebbe accadere invece?**

Il link dev essere allineato al testo

**Screenshots**

<img width="1113" alt="Screenshot 2021-05-22 at 12 10 33" src="https://user-images.githubusercontent.com/4223655/119222950-21b30180-baf7-11eb-8552-9d274faa88a5.png">

**Comment by gpirrotta** [comment]
Chiuso con PR #53
