### ISSUE TITLE
Link a opendatasicilia in dashboard

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#54]
Bouonasera! Secondo voi è necessario inserire qualche riferimento a opendatasicilia nelle [dashboards](https://datastudio.google.com/s/hTEGek398u0)?

**Comment by aborruso** [comment]
Probabilmente in una release 2.0, queste dashboard sono da inglobare in un template minimale HTML.

Con ad esempio un footer con un po' di info.

**Comment by gpirrotta** [comment]
Nelle dashboard secondo me andrebbe inserito il loghetto di ODS con la dicitura "Un progetto di Open Data Sicilia" con il link di rimando a https://informacovid.opendatasicilia.it

**Comment by dennisangemi** [comment]
> Nelle dashboard secondo me andrebbe inserito il loghetto di ODS con la dicitura "Un progetto di Open Data Sicilia" con il link di rimando a https://informacovid.opendatasicilia.it

Fatto!

![image](https://user-images.githubusercontent.com/77018886/132903581-28d87104-4f41-4303-a6f9-ceeaf6f72aaf.png)

p.s. avevo dimenticato alcune issue
