### ISSUE TITLE
copia WEB Archive delle vecchie ordinanze su COVID 19

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/informa-covid19#57]
Da pochissimo la Regione Siciliana ha un nuovo sito dove pubblica le ordinanze sul COVID-19, 
per evitare di perdere i PDF delle vecchie ordinanze, forse sarebbe una buona idea creare un archivio.

Apro issue qui perché non esiste un repo sulle zone rosse e relative ordinanze.

grazie

**Comment by aborruso** [comment]
fatto 

![image](https://user-images.githubusercontent.com/30607/124634672-e4c48380-de86-11eb-8810-0016f39bf427.png)
