### ISSUE TITLE
IPA email comuni

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#62]
Scaricare e organizzare indirizzi email dei comuni da IPA: https://indicepa.gov.it/ipa-dati/group/indirizzi-elettronici

**Comment by aborruso** [comment]
Guardati anche questo dataset generale https://indicepa.gov.it/ipa-dati/dataset/amministrazioni

**Comment by dennisangemi** [comment]
Grazie mille @aborruso, sto lavorando sul file suggerito da te e ho notato che per alcuni comuni sono disponibili più indirizzi email pertanto vi domando: preferiamo indirizzare la mail al **protocollo** o al/la **sindaco/a**?

**Comment by gpirrotta** [comment]
Ciao @dennisangemi,
secondo me il canale da preferire (se presente)  è il **protocollo** sia perché rappresenta la porta ufficiale di tutte le istanze in ingresso di una PA (e ha valenza certativa), sia perché spesso, dopo la protocollazione, il sistema di gestione documentale della PA notifica al mittente l'avvenuta presa in carico.

my2c
Giovanni

**Comment by aborruso** [comment]
Mi unisco a Giovanni

**Comment by dennisangemi** [comment]
Grazie @gpirrotta e @aborruso. A questo punto credo di dover invocare il vostro aiuto. Di seguito una piccola descrizione degli step effettuati e delle difficoltà riscontrate:

1. Ho scaricato il file .txt da https://indicepa.gov.it/ipa-dati/dataset/amministrazioni 
2. Aperto il file in excel (gsheet mi dava problemi)
3. Filtrato il dataset per ottenere solo righe che cominciano con "Comune di"
4. Esportato il file con solo i comuni ed importato in [gsheet ](https://docs.google.com/spreadsheets/d/1B-795olRhZaTCw4zIdw8Jm28DfK038VWLL8De1atLBs/edit?usp=sharing)
5. Utilizzato qualche query in modo tale da escludere le PEC e forzare il lowercase degli indirizzi
6. Organizzato il dataset in 2 formati: long (`no_pec_long`) e wide (`no_pec_wide`)

Adesso mi trovo in difficoltà per selezionare gli indirizzi "main", ovvero quelli a cui inviare la nostra email. Avete qualche idea per evitare di selezionarli a mano?

p.s. 
Nel foglio `no_pec_wide_con_anagrafica` ho provato ad integrare [l'anagrafica comuni](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/dati-popolazione/elenco-comuni-italiani.csv)  preparatada @gabacode (grazie) così da avere il codice istat per ogni comune ma alcune righe restituiscono degi errori della fx `vlookup`. Per adesso eviterei di impiegare tanto tempo per risolvere questi errori e integrare i codici istat nell'output. Tutti/e d'accordo?

**Comment by aborruso** [comment]
Caro @dennisangemi io farei semplicemente che se un comune ha 5 email, e una contiene "protocollo", si prenda quella, altrimenti la prima in elenco.

E poi in realtà il dataset da usare è un altro, perché molto più ricco, consente di fare bene i filtri e di avere i codici: https://indicepa.gov.it/ipa-dati/dataset/enti

Ti faccio una pre lavorazione e torno qui

**Comment by dennisangemi** [comment]
Ecco [qui ](https://docs.google.com/spreadsheets/d/1GYNcVhSGBbDod3E77NruyljbvOzd6y_UvfoJPqmSy9M/edit?usp=sharing) l'elaborazione del [dataset enti](https://indicepa.gov.it/ipa-dati/dataset/enti). Credo che il risultato sia esattamente uguale al precedente (countunique 5264) ma adesso abbiamo i codici istat :)

**Comment by aborruso** [comment]
Ciao @dennisangemi, vedo che ti sei mosso comunque.

Ho prodotto una [prima versione di script](https://github.com/opendatasicilia/informa-covid19/blob/main/script/anagrafiche/ipa.sh) che scarica gli enti e produce l'output che cerchiamo. Lo fa in questo modo:

- filtra il `Codice_Categoria` uguale a `L6`, i comuni. Purtroppo qui la categorizzazione a monte sembra sbagliata e quindi filtro tutti quelli nella descrizione hanno `^comune`;
- poi rimuovo tutte  le mail [che sembrano PEC](https://github.com/opendatasicilia/informa-covid19/blob/main/script/anagrafiche/ipa.sh#L27) (millemila modi, `postacert`, `certym`, ecc.);
- poi estraggo tutte i comuni che hanno un solo indirizzo o che hanno l'email che contiene `protocol`;
- poi estraggo la prima delle email da gli altri comuni rimasti.

In output questo https://github.com/opendatasicilia/informa-covid19/blob/main/dati/anagrafiche/comuniIPA-noPEC.csv

**Comment by dennisangemi** [comment]
Aggiornamento delle 15:50: 
**Ci sono riuscito!**

Nel foglio `selezione` di [questo ghseet](https://docs.google.com/spreadsheets/d/1GYNcVhSGBbDod3E77NruyljbvOzd6y_UvfoJPqmSy9M/edit?usp=sharing) trovate gli indirizzi email "main". Ho giocato un po' con regexmatch per suddividere gli indirizzi email in protocollo, info, sindaco, comune o altro e ho seguito questo ordine per selezionarli

**Comment by dennisangemi** [comment]
> Ciao @dennisangemi, vedo che ti sei mosso comunque.
> 
> Ho prodotto una [prima versione di script](https://github.com/opendatasicilia/informa-covid19/blob/main/script/anagrafiche/ipa.sh) che scarica gli enti e produce l'output che cerchiamo. Lo fa in questo modo:
> 
> * filtra il `Codice_Categoria` uguale a `L6`, i comuni. Purtroppo qui la categorizzazione a monte sembra sbagliata e quindi filtro tutti quelli nella descrizione hanno `^comune`;
> * poi rimuovo tutte  le mail [che sembrano PEC](https://github.com/opendatasicilia/informa-covid19/blob/main/script/anagrafiche/ipa.sh#L27) (millemila modi, `postacert`, `certym`, ecc.);
> * poi estraggo tutte i comuni che hanno un solo indirizzo o che hanno l'email che contiene `protocol`;
> * poi estraggo la prima delle email da gli altri comuni rimasti.
> 
> In output questo https://github.com/opendatasicilia/informa-covid19/blob/main/dati/anagrafiche/comuniIPA-noPEC.csv

Wow @aborruso ! Adesso capisco @pigreco quando dice "scrivo uno script bash e sono da te"! che figata

**Comment by aborruso** [comment]
@dennisangemi probabilmente ho perso tempo :) , ho letto che hai risolto.

Non faccio più nulla per il momento

**Comment by dennisangemi** [comment]
Avendo completato task e ottenuti due risultati differenti chiudo issue (ringraziando @aborruso) per tornare alla #61 .

Gli output prodotti:
- [output di @aborruso ](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/anagrafiche/comuniIPA-noPEC.csv)
- [output mio](https://docs.google.com/spreadsheets/d/e/2PACX-1vTlY2Zcr8JAVtjafBtrrPVs5PPJDu4Z1g-2XaoKTKlCTajb8gar8AyewjCRcfYIypCF8i-mFdn8OX5Z/pub?gid=1766613765&single=true&output=csv) derivante da [questo gsheet](https://docs.google.com/spreadsheets/d/1GYNcVhSGBbDod3E77NruyljbvOzd6y_UvfoJPqmSy9M/edit?usp=sharing)

Se necessario carico il csv in [anagrafiche](https://github.com/opendatasicilia/informa-covid19/tree/main/dati/anagrafiche). 

Ho selezionato, tra gli indirizzi disponibili per ogni comune, quello più "appropriato" secondo il seguente ordine di importanza: **protocollo > info > sindaco > segreteria > urp > comune o altro**. Pensate possa andare bene?

**Comment by aborruso** [comment]
@dennisangemi usiamo il tuo, è più curato
