### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#65]
Parlando con @angelogulina, ci siamo resi conto che abbiamo dimenticato di inserire una privacy policy nel sito di [informacovid](https://informacovid.opendatasicilia.it/). Dovrebbe essere necessaria in quanto abbiamo attivato analytics (giusto?). 

Io non ho idea di cosa sia, come si faccia e se sia strettamente necessaria. @gabacode ci illumini per favore?

**Comment by gabacode** [comment]
@dennisangemi come forse saprai, non sono proprio un esperto in materia 🏴‍☠️
Farò delle ricerche a riguardo, qualora ci fosse qualcuno con piu esperienze a riguardo, sarò felice di implementare un banner/pagina collegato al già presente bottone "opt-out". Al momento siamo con un semplice Universal Analytics (UA)

**Comment by gabacode** [comment]
Ho aggiunto una Cookie Policy su template di Joska e design di @dennisangemi . Adesso il consenso dev'essere esplicitamente espresso, altrimenti non partono gli analytics. L'indirizzo email e ulteriori dati sul titolare della Privacy vanno inseriti in [questo file](https://github.com/opendatasicilia/informa-covid19/blob/main/src/components/Privacy.svelte).

**Comment by dennisangemi** [comment]
Fantastico! Grazie
