### ISSUE TITLE
Predisporre CSV comuni italiani 

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/informa-covid19#7]
Predisporre un file **CSV** da caricare su github dei comuni italiani, con le seguenti informazioni:

- [x] regione_codice
- [x] regione_denominazione
- [x] provincia_sigla
- [x] provincia_denominazione
- [x] comune_codice_istat
- [x] comune_denominazione
- [x] latitudine
- [x] longitudine
- [x] popolazione

**Comment by gabacode** [comment]
Grazie @gpirrotta . Mi sto basando sull'[Elenco codici statistici e denominazioni delle unità territoriali](https://www.istat.it/it/archivio/6789), sulla [Popolazione residente al 1° gennaio 2020](http://dati.istat.it/index.aspx?queryid=19101), calcolando le coordinate con [GeoPy](https://pypi.org/project/geopy/).
In totale si tratta di 7904 Comuni. Il numero di abitanti in 11 nuovi comuni non era presente nel foglio dell'ISTAT, quindi li ho aggiunti manualmente. In particolare si tratta dei Comuni di:

- Borgo d'Anaunia
- Novella
- Ville di Fiemme
- Doberdò del Lago
- San Floriano del Collio
- Savogna d'Isonzo
- Duino Aurisina
- Monrupino
- San Dorligo della Valle
- Sgonico
- Misiliscemi

Ho uppato il file [qui](https://github.com/opendatasicilia/informa-covid19/blob/main/dati-popolazione/elenco-comuni-italiani.csv).

**Comment by aborruso** [comment]
@gabacode alcune note/proposte:

- al codice ISTAT, per renderlo più standard, è meglio applicare uno 0 padding e portarlo 6 caratteri (ad esempio da `1801` a `001801`);
- potremmo mettere in una cartella script, il codice con cui produciamo i file di output, in modo da potere ripetere autonomamente pipeline, aggiungere pezzi, ecc.. Quindi qui ad esempio `script/dati-popolazione`;
- farei una cartella dati, e ci metterei questa cartella che hai creato oggi. Quindi qui ad esempio `dati/dati-popolazione`

Il primo è un punto importante. Gli altri due, sono tante delle opzioni possibili

**Comment by pigreco** [comment]
@gabacode il Comune di `Misiliscemi` è nato da pochissimo (come porzione del Comune di Trapani) e ho visto che hai messo la popolazione 8.669, mentre la popolazione di Trapani è 65.841; forse occorre togliere la popolazione di Misiliscemi da quella di Trapani?

**Comment by dennisangemi** [comment]
Buongiorno, confrontando le informazioni che dovrebbero essere presneti nel CSV suggerite da @gpirrotta e lo schema dati unico di @gabacode, ho notato che nel CSV anagrafica comuni è assente il campo "distretto". Come procedere? Eliminiamo il campo "distretto" dallo schema dati?

**Comment by dennisangemi** [comment]
In gsheet, quando uso vlookup per attingere tutte le info dal file che sta preparando @gabacode , è necessario (se non sbaglio) che la prima colonna sia "comune_denominazione". 

Che ne dite di modificare l'ordine delle colonne del CSV che sta preparando @gabacode come di seguito?

- comune_denominazione
- comune_codice_istat
- latitudine
- longitudine
- popolazione
- provincia_denominazione
- provincia_sigla
- regione_denominazione
- regione_codice

**Comment by gabacode** [comment]
> @gabacode alcune note/proposte:
> 
> * al codice ISTAT, per renderlo più standard, è meglio applicare uno 0 padding e portarlo 6 caratteri (ad esempio da `1801` a `001801`);
> * potremmo mettere in una cartella script, il codice con cui produciamo i file di output, in modo da potere ripetere autonomamente pipeline, aggiungere pezzi, ecc.. Quindi qui ad esempio `script/dati-popolazione`;
> * farei una cartella dati, e ci metterei questa cartella che hai creato oggi. Quindi qui ad esempio `dati/dati-popolazione`
> 
> Il primo è un punto importante. Gli altri due, sono tante delle opzioni possibili

Ho sistemato e aggiunto degli [scripts](https://github.com/opendatasicilia/informa-covid19/tree/main/script/dati-popolazione) per automatizzare il processo. Il processo dura circa un'ora, rispettando il timeout default di GeoPy. I nuovi files generati aggiungeranno il padding 0, ma al momento non contengono i dati relativi alla popolazione di Borgo d'Anaunia, Novella, Ville di Fiemme e Misiliscemi (settati a 0), non essendo contenuti nei dati [ISTAT 2020](http://demo.istat.it/pop2020/dati/comuni.zip). Questa volta ho utilizzato il dataset contenuto in [questo link](http://demo.istat.it/pop2020/dati/comuni.zip), e raggruppato per comune_codice_istat, prima avevo raggruppato per comune_denominazione, il che portava qualche problema in termine di Comuni con lo stesso nome, adesso risolto. Andrebbe generato il nuovo elenco-comuni-italiani.csv

> @gabacode il Comune di `Misiliscemi` è nato da pochissimo (come porzione del Comune di Trapani) e ho visto che hai messo la popolazione 8.669, mentre la popolazione di Trapani è 65.841; forse occorre togliere la popolazione di Misiliscemi da quella di Trapani?

E' una buona idea! Pero' ho preso il numero 8.669 da Wiki, con fonte [Itacanotizie.it](https://itacanotizie.it/2021/02/03/lars-ufficializza-la-nascita-del-comune-di-misiliscemi-le-reazioni-della-politica-locale/) mentre la popolazione di Trapani è [ISTAT 2020](http://demo.istat.it/pop2020/dati/comuni.zip). Non so quanto possa essere attendibile, cosa conviene fare?

> Buongiorno, confrontando le informazioni che dovrebbero essere presneti nel CSV suggerite da @gpirrotta e lo schema dati unico di @gabacode, ho notato che nel CSV anagrafica comuni è assente il campo "distretto". Come procedere? Eliminiamo il campo "distretto" dallo schema dati?

Effettivamente, pensando ai Comuni per l'immissione dati, a questo punto penso sia più logico eliminare il campo "distretto" e aggiungere magari "provincia" (es. "PA", "EN" etc..) che ne pensate?

> In gsheet, quando uso vlookup per attingere tutte le info dal file che sta preparando @gabacode , è necessario (se non sbaglio) che la prima colonna sia "comune_denominazione".
> 
> Che ne dite di modificare l'ordine delle colonne del CSV che sta preparando @gabacode come di seguito?
> 
> * comune_denominazione
> * comune_codice_istat
> * latitudine
> * longitudine
> * popolazione
> * provincia_denominazione
> * provincia_sigla
> * regione_denominazione
> * regione_codice

Per me va bene, si può aggiungere un riordine delle colonne alla fine dello script [main.py](https://github.com/opendatasicilia/informa-covid19/blob/main/script/dati-popolazione/main.py), che al momento "segue" un pò l'ordine ISTAT. Che ne pensate? @aborruso @gpirrotta @pigreco

**Comment by dennisangemi** [comment]
> Effettivamente, pensando ai Comuni per l'immissione dati, a questo punto penso sia più logico eliminare il campo "distretto" e aggiungere magari "provincia" (es. "PA", "EN" etc..) che ne pensate?

A me sembra un'ottima idea!
