### ISSUE TITLE
Aggiungere dati vaccini a dashboard InformaCOVID

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#72]
Qui il primo esempio https://informacovid.opendatasicilia.it/d/barrafranca/

**Comment by dennisangemi** [comment]
Sarebbe possibile inserire i dati sui vaccini solo per i comuni siciliani pertanto, essendo il template pensato per qualsiasi comune italiano, si rinuncia all'esecuzione del task.

**Comment by aborruso** [comment]
> Sarebbe possibile inserire i dati sui vaccini solo per i comuni siciliani pertanto, essendo il template pensato per qualsiasi comune italiano, si rinuncia all'esecuzione del task.

Non l'ho capita.

Se devi mettere in una dasboard italiana i dati dei vaccini, ma hai soltanto i vaccini della Sicilia, sei bloccato.
Ma qui non è il contrario?

**Comment by dennisangemi** [comment]
Ciao @aborruso , si tratta esattamente del caso che citi: la dashboard è pensata per tutti i comuni italiani ma abbiamo soltanto i vaccini della Sicilia quindi siamo bloccati.

Sbaglio qualcosa?

**Comment by aborruso** [comment]
Ok, ma al momento su informacovid non ci sono soltanto comuni siciliani? Ok il template è mondiale, ma i tipi di dato non sono coerenti tra loro (regione sicilia e basta)?

**Comment by dennisangemi** [comment]
> Possiamo mettere una condizione sulla Dashboard del tipo "se i dati con tale codice ISTAT sono presenti => allora mostra la tabella vaccini" altrimenti mostra una div vuota ?

Non so se si può fare una cosa del genere in GDS però sicuramente si può fare nello sheet ad esso collegato (in termini leggermente diversi) : con una if function possiamo mostrare o non mostrare i dati di una specifica label (ad esempio vaccini) in base al codice Istat ma con il presupposto che ci sia già "lo spazio dedicato" in dashboard

**Comment by dennisangemi** [comment]
> Ok, ma al momento su informacovid non ci sono soltanto comuni siciliani? Ok il template è mondiale, ma i tipi di dato non sono coerenti tra loro (regione sicilia e basta)?

Yes, hai ragione: al momento su informaCOVID ci sono solo comuni siciliani. 

Qui due considerazioni:
- modificando adesso il template di Google sheet (inserendo una if function) non si modificherebbero gli sheet già esistenti e duplicati dai comuni attualmente aderenti quindi si dovrebbero modificare manualmente (è una cosa che si può fare, alla fine non sono tantissimi)
- Alcuni comuni potrebbero non volere in dashboard I dati sui vaccini rappresentati con una semplice etichetta perché ritengono giustamente siano necessarie ulteriori precisazioni (utile parere di @peppelamensa )

**Comment by aborruso** [comment]
Ciao, io mi fermo qui con i consigli su questo punto, perché mi manca la
conoscenza della logica del sistema e degli obiettivi.

Grazie per le info

-- 
___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino
