### ISSUE TITLE
Embedded links in map

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/informa-covid19#79]
Segnalazione di @nazzaprinz:

>Ragazzi, mi sono accorto che cliccando su qualsiasi flag di un Comune, il sistema riporta sempre i dati di Caltanissetta.

http://informacovid.opendatasicilia.it

**Comment by aborruso** [comment]
Sembra che passi sempre lo stesso id.

La tabella dati sorgente qual è?

![image](https://user-images.githubusercontent.com/30607/143781413-7ad03761-37bc-486a-88ad-ab99addf50f2.png)

**Comment by dennisangemi** [comment]
Non è la mappa il problema. Sembra che si siano rotti i link per il redirect 

Vd. http://informacovid.opendatasicilia.it/d/niscemi 

Tra un po' dovrei riuscire a mettermi al pc per controllare meglio (sono quasi sicuro del fatto che il problema provenga da un mio sheet). Se io non trovo il problema sarò costretto ad evocare @gabacode

**Comment by dennisangemi** [comment]
Sono appena riuscito a risolvere il problema: pare Google Data Studio non supporti più l'embedding con il pattern che utilizzavamo per i comuni di della provincia di caltanissetta quindi ho modificato quei link abilitando i "[custom bookmark links](https://support.google.com/datastudio/answer/7664330#zippy=%2Cin-this-article)". 

Adesso la mappa sembra funzionare tuttavia compare questo messaggio di errore:

![image](https://user-images.githubusercontent.com/77018886/143789282-30521d06-f361-4e86-bb3d-2c10e00da661.png)

@gbvitrano per favore, quando puoi, dai un'occhiata? thx


p.s.
@gabacode puoi stare tranquillo, i tuoi link funzionano alla perfezione e non avevano nulla di sbagliato.

**Comment by gbvitrano** [comment]
risolto l'errore nell'import Umap

**Comment by dennisangemi** [comment]
Grazie @gbvitrano
