### ISSUE TITLE
Predisposizione di un Google Form per i sindaci

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/informa-covid19#8]
Predisposizione di un Google Form in grado di far selezionare la regione e il comune di appartenenza ai sindaci e generare il template customizzato di Google Sheets / Google Data Studio per le dashboard.

**Comment by dennisangemi** [comment]
Purtroppo in google form non è possibile realizzare dropdown menu dipendenti uno dall'altro come conferma questa [discussione](https://stackoverflow.com/questions/58418531/dynamic-dependent-dropdowns-on-google-form). Sarebbe stato utile per selezionare la regione e poi il comune. Ho in mente una soluzione che scrivo qui domani

**Comment by aborruso** [comment]
Io ho usato spesso i form basati su enketo, che fanno cose straordinarie, tra cui form con input in dipendenza tra loro: https://enketo.org/#tools

Tra questi vi consiglio ona e kobo.

Se non avete super fretta, do una mano

**Comment by gpirrotta** [comment]
> Tra questi vi consiglio ona e kobo.
Grazie Andrea gli dò un'occhiata.

> Se non avete super fretta, do una mano
Non c'è una data di scadenza e sì, il tuo contributo, come quello di tutta la comunità, sarebbe importante 😍

**Comment by aborruso** [comment]
Su t'ansignari ci sono due piccole ricette con dei casi d'uso geo https://tansignari.opendatasicilia.it/tags/odk/

Nel week-end vi condivido un form ciao mondo, con il filtro regione/provincia/comune

**Comment by aborruso** [comment]
Ciao,
ecco un esempio di form fatto con enketo: https://enketo.ona.io/x/XG7lIILX

Per crearlo, basta definire un modello tramite foglio elettronico: [questo](https://github.com/opendatasicilia/informa-covid19/files/6401659/IC19_Form.xls) quello usato, basato su [queste specifiche](https://xlsform.org/en/).

Quindi diciamo che questa era lo **Scenario 4**.

E poi ci sarebbe lo **Scenario 5**. Non usare un form, ma usare un foglio elettronico online, con regoline, blocchi, menu a tendina

**Comment by gpirrotta** [comment]
Grazie @aborruso,
lo Scenario 5 è quello che inizialmente si voleva evitare, cioè far *mettere mani* ai sindaci nel foglio Google. Allo stato tempo ritengo però la tua proposta il giusto compromesso tra fattibilità e rapidità. Thanks.

**Comment by dennisangemi** [comment]
![image](https://user-images.githubusercontent.com/77018886/116693925-dbb6c200-a9be-11eb-844c-2ed397daef61.png)
Abbiamo pensato a una soluzione del genere: menu a tendina tramite convalida dati. Pensate possa essere quella definitiva? Chiudo issue?

**Comment by aborruso** [comment]
@dennisangemi purtroppo vedo solo uno screenshot, mentre voi avete un quadro complessivo.
In ogni caso, se per voi è ok, per me è ok.

Grazie

**Comment by dennisangemi** [comment]
Perdonatemi, ho dimenticato di condividere [link al foglio](https://docs.google.com/spreadsheets/d/19CDsgmt68JQ3NbDiZar9IaAh6kMI2V5i9d5hwbHzCWA/edit?usp=sharing)

**Comment by aborruso** [comment]
Grazie @dennisangemi mi sembra ok.

Per me un foglio elettronico ben strutturato, nel rapporto vantaggi/svantaggi, e con tutte le premesse fatte in questo progetto, è sicuramente migliore di un google form.

Se per voi è ok, chiudete

**Comment by angelogulina** [comment]
Siete sicuri che un foglio excel abbia la stessa affordance di un form?

Domanda da 1000 dollari: è possibile usare altri Form, non Google, che buttino i dati sullo Sheet? 🤔

**Comment by gpirrotta** [comment]
Sì, esistono altre soluzioni, @aborruso proponeva ENKETO e ONA. Tuttavia, per semplificare il più possibile il dipendente comunale, in questa prima fase stiamo utilizzando un sistema a tendina direttamente nello sheet, come [questo](https://docs.google.com/spreadsheets/d/19CDsgmt68JQ3NbDiZar9IaAh6kMI2V5i9d5hwbHzCWA/edit?usp=sharing).
Successivamente si potranno valutare approcci migliori.

**Comment by angelogulina** [comment]
Grazie @gpirrotta. Il sistema a tendina lo avevo visto. Quale ruolo bisogna avere per smuovere la tendina?

**Comment by dennisangemi** [comment]
@angelogulina pensi ancora possa essere una soluzione poco user friendly ? Teniamo aperta questa issue per altre idee?

**Comment by angelogulina** [comment]
@dennisangemi il modo migliore per saperlo alla fine sarà sentire cosa dicono le persone che la usano. In caso di feedback negativi, possiamo aprire un'altra Issue.
